name: Flutter Multi-Platform Build

on:
  workflow_dispatch:

jobs:
  # Build Android APK and AAB
  build-android:
    name: 🚀 Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get

      # Build APK for all architectures
      - run: flutter build apk --release --split-per-abi
      
      # Build AAB
      - run: flutter build appbundle --release

      # Debug: List build outputs
      - run: |
          echo "Listing APK files:"
          ls -la build/app/outputs/flutter-apk/
          echo "Listing AAB files:"
          ls -la build/app/outputs/bundle/release/

      # Upload APKs
      - name: Upload APKs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/*.apk
          tag: v1.0
          overwrite: true
          body: "Android APKs (all architectures) for this release."

      # Upload AAB
      - name: Upload AAB to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/bundle/release/*.aab
          tag: v1.0
          overwrite: true
          body: "Android AAB for this release."
